version: "3.8"
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # image: 664582.dkr.ecr.eu-centrl-1.amazonaws.com/my-app:1.0
  # ports:
  # - 3000:3000
  mongodb: # maps to the container name
    image: mongo
    ports:
      - 27017:27017
    environment: # enviroment viriables
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes: # lists of volumes
  mongo-data:
    driver: local
